name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android licenses
      run: |
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

    - name: Generate buildozer.spec if not present
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
          # You might want to adjust the buildozer.spec default settings
          # For example, set the title, package.name, etc.
          # But note: this will generate a new one. It's better to commit one to the repo.
        fi

    - name: Build APK with buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
