name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git unzip openjdk-17-jdk
        pip install buildozer cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: |
        yes | buildozer android platform --accept-license

    - name: Build APK
      run: buildozer android debug

    # FIXED VERSION BELOW (v3 → v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
